### PR TITLE
Alliance University - Arjun kumar smart contract

### PR DESCRIPTION
**Pull request by Arjxm**
# PR Submission Checklist

Thank you for your PR.  Please select from the following:

- [ ]  This PR submits only an Article
- [ ]  This PR submits a Tutorial with an Article
- [ ]  This PR requests modification to an existing Tutorial / Article

If this PR is a Tutorial with an Article, please select from the following as well:

- [ ]  What level does the Tutorial serve:
    - [.]  Beginner (from nil experience in the subject to 1 year)
    - [ ]  Intermediate (from nil experience in the subject to 1 year)
    - [ ]  Advanced

In respect of the Article, please submit the following, if applicable:

- [ ]  Please confirm that you have mentioned yourself as the author of the Article
- [ ]  You are more than welcome to also give links to your social media handles too, for reference

Alliance university Smart contract assessment by Arjun kumar

### CODE REVIEW

**Comment by amateur-dev** [comment]
@Iam-Arjun23 Nice work.  I will review this in more depth.

**Comment by Iam-Arjun23** [comment]
Thank you for taking the time to review my work. I appreciate your feedback and would be happy to discuss this more in-depth.

**Comment by chandn0** [comment]
@Iam-Arjun23 Add comments in the contract. and Remove the ganache network from Hardhat.config file.

**Comment by Iam-Arjun23** [comment]
@chandn0 comments are added in the contract and hardhat.config file also fixed.

**Pull request closed without merging**
