### PR TITLE
Adding Project Cryptocurrency Transfer App

### PR DESCRIPTION
**Pull request by Moksh91119**
# PR Submission Checklist

Thank you for considering this PR. Please select from the following:

- [ ] This PR submits only an Article
- [x] This PR submits a Tutorial with an Article
- [ ] This PR requests modification to an existing Tutorial / Article

If this PR is a Tutorial with an Article, please select from the following as well:

- [ ] What level does the Tutorial serve:
    - [ ] Beginner (from nil experience in the subject to 1 year)
    - [x] Intermediate (from nil experience in the subject to 1 year)
    - [ ] Advanced

In respect of the Article, please submit the following, if applicable:

- [x] Please confirm that you have mentioned yourself as the author of the Article
- [x] You are more than welcome to also give links to your social media handles too, for reference

Social Media Links:
- Portfolio: [itsmemoksh.in](https://itsmemoksh.in/)
- LinkedIn: [Moksh Jain](https://www.linkedin.com/in/moksh-jain-51271b194/)
- Instagram: [adios3615](https://www.instagram.com/adios3615/)

### CODE REVIEW

**Comment by chandn0** [comment]
Hi  @Moksh91119, 

Thank you for submitting your project.  
The website link you have shared in the readme file is not working, please reshare it.

**Comment by Moksh91119** [comment]
Hello @chandn0 ,
Check the website link again, it should work now

**Comment by chandn0** [comment]
@Moksh91119 Can you please make the website public?
image

CC: @sanamumer

**Comment by Moksh91119** [comment]
@chandn0 , Appreciate you pointing out the issue. I've fixed it by making the website public. Kindly to take a look and make sure everything's running smoothly.

**Comment by sanamummer** [comment]
Alright.

**Comment by amateur-dev** [comment]
Hi @Moksh91119 

Thank you for the PR.  I like what you've done.  I will work with my team to create an article out of this, and we will give you the due credit for this work.  We will also evaluate this work from a job point of view and get back to you.

**Pull request closed without merging**
