### PR TITLE
BuildBearLab Job Task

### PR DESCRIPTION
**Pull request by ShivamAgarwal-code**
Role Applied: Junior Frontend Developer

Done with the task :)

### CODE REVIEW

**Comment by chandn0** [comment]
Hi  @ShivamAgarwal-code ,

Thank you for submitting your project. To help us better understand your work, please provide a clear explanation in the README file. Additionally, please deploy your project to Vercel and share the link for further evaluation.

**Comment by ShivamAgarwal-code** [comment]
Done @chandn0

**Comment by sanamummer** [comment]
Hey @ShivamAgarwal-code ! UI looks good but can you integrate new/existing smart contracts into your projects? Or at least wallet connection.

**Comment by ShivamAgarwal-code** [comment]
@ShivamAgarwal-code yes yes I can integrate that, actually role I applied for is frontend developer so that why I made the frontend only.
Here is one of my project: https://nft2-marketplace.vercel.app/
with wallet connection..

**Pull request closed without merging**
